apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eventarz-zuul
  name: eventarz-zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventarz-zuul
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eventarz-zuul
    spec:
      containers:
        - image: eventarzcontainerregistry.azurecr.io/eventarz-zuul:latest
          name: eventarz-zuul
          resources: {}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eventarz-zuul
  name: eventarz-zuul
spec:
  ports:
    - name: 8443-8443
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: eventarz-zuul
  type: ClusterIP
