spring:
  cloud.loadbalancer.ribbon.enabled: false
  application:
    name: "eventarz-zuul"

server:
  port: 8443
  use-forward-headers: true
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/eventarz.p12
    key-store-password: password
    key-alias: eventarz
    enabled: true

eureka:
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

ribbon:
  ReadTimeout: 60000

zuul:
  ignoredServices: '*'
  debug.request: true
  add-proxy-headers: true
  sensitive-headers:
  routes:
    gateway:
      path: /gateway/**
      serviceId: eventarz-gateway
    application:
      path: /**
      serviceId: eventarz-application

logging:
  pattern:
    #    Simplified logging pattern without PID, thread name and logger name to make it readable on screenshots
    console: "${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
  level:
    org.springframework.cloud.netflix: DEBUG
